name: Build, Push and Deploy to Cloud Run

on:
  push:
    branches:
      - fix/yarn-lock

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-east1
  GAR_LOCATION: us-east1
  APP_NAME: lapisdcor-app
  REPO_NAME: lapisdcor-repo
  IMAGE_NAME: lapisdcor

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_DEPLOY_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Authorize Docker push
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Calculate Image Tag
        id: image_tag
        run: |
          IMAGE_PATH="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}"
          TAG="${{ github.sha }}"
          echo "image_with_tag=${IMAGE_PATH}:${TAG}" >> $GITHUB_OUTPUT
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.image_tag.outputs.image_with_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name:  Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.APP_NAME }} \
            --image=${{ steps.image_tag.outputs.image_with_tag }} \
            --region=${{ env.GCP_REGION }} \
            --platform=managed \
            --project=${{ env.GCP_PROJECT_ID }} \
            --quiet \
            --port=3000 \
            --allow-unauthenticated